version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
    allow:
      - dependency-type: "direct"
        update-types:
          - "version-update:semver-patch"
          - "version-update:semver-minor"
  - package-ecosystem: "bundler"
    directory: "/"
    schedule:
      interval: "weekly"
    allow:
      - dependency-type: "direct"
        update-types:
          - "version-update:semver-patch"
          - "version-update:semver-minor"
