require: rubocop-rails

AllCops:
  Exclude:
    - 'test/**/*'
    - 'spec/**/*'
    - 'db/**/*'
    - 'config/**/*'
    - 'spec/**/*'
    - 'bin/*'
    - 'config.ru'
    - 'Gemfile'
    - 'Rakefile'

Style/FrozenStringLiteralComment:
  Enabled: false

Style/Documentation:
  Enabled: false
