FROM internetee/ruby:3.0-buster
ARG RAILS_ENV
ARG SECRET_KEY_BASE
ARG APP_DBHOST

ENV RAILS_ENV "$RAILS_ENV"
ENV SECRET_KEY_BASE "$SECRET_KEY_BASE"
ENV APP_DBHOST "$APP_DBHOST"
RUN npm install -g yarn@latest
WORKDIR /opt/webapps/app
COPY Gemfile Gemfile.lock ./
RUN gem install bundler && bundle install --jobs 20 --retry 5
COPY package.json yarn.lock ./
RUN yarn install --check-files
COPY . .

EXPOSE 3000
